open Constants
open Learning
open Srs

let str = React.string

type credit = {
  name: string,
  detail: string,
  url: string,
}

@react.component
  let make = (
    ~learnedCount,
    ~stats: reviewStats,
    ~dashboard: srsDashboard,
    ~settings: reviewSettings,
    ~onSettingsChange,
    ~onShowStudied,
    ~onDataImported,
  ) => {
    let learned = if learnedCount > kanjiMasteryTarget {kanjiMasteryTarget} else {learnedCount}
    let totalReviews = stats.correct + stats.wrong
    let last100Wrong = stats.last100Total - stats.last100Correct
    let chartStats = loadKanjiChartStats()
    let setRequiredStreak = value =>
      onSettingsChange({...settings, requiredCorrectStreak: value})
    let quickReviewKindChoices = [
      "kanji_to_kana",
      "kanji_to_meaning",
      "kana_to_meaning",
      "meaning_to_kanji",
      "meaning_to_kana",
    ]
    let hasQuickReviewKind: (array<string>, string) => bool = %raw(`(kinds, kind) => kinds.includes(kind)`)
    let addQuickReviewKind: (array<string>, string) => array<string> = %raw(`(kinds, kind) => kinds.includes(kind) ? kinds : kinds.concat(kind)`)
    let removeQuickReviewKind: (array<string>, string) => array<string> = %raw(`(kinds, kind) => kinds.filter(item => item !== kind)`)
    let toggleQuickReviewKind = kind => {
      let enabled = hasQuickReviewKind(settings.quickReviewKinds, kind)
      let nextKinds =
        if enabled {
          let removed = removeQuickReviewKind(settings.quickReviewKinds, kind)
          if Array.length(removed) <= 0 {
            settings.quickReviewKinds
          } else {
            removed
          }
        } else {
          addQuickReviewKind(settings.quickReviewKinds, kind)
        }
      onSettingsChange({...settings, quickReviewKinds: nextKinds})
    }
    let splitRow = (label, correct, wrong) => {
      let total = correct + wrong
      <SplitRow key={label}>
        <span> {str(label)} </span>
        <Muted>
          {str(
            percentString(correct, total) ++
            " (" ++ Int.toString(correct) ++ " / " ++ Int.toString(total) ++ ")",
          )}
        </Muted>
      </SplitRow>
    }
    let countRow = (label, count) =>
      <SplitRow key={label}>
        <span> {str(label)} </span>
        <Muted> {str(Int.toString(count))} </Muted>
      </SplitRow>
    let credits = [
      {
        name: "KanjiVG",
        detail: "Stroke, drawing, and radical-structure source. Copyright Ulrich Apel, CC BY-SA 3.0.",
        url: "https://kanjivg.tagaini.net/",
      },
      {
        name: "Ryōkan Taigu calligraphy texture",
        detail: "Abstract ink-grain texture derived without lettering from the Met Open Access public-domain image of Ryōkan Taigu's One Hundred Flowers of Spring.",
        url: "https://www.metmuseum.org/art/collection/search/902225",
      },
      {
        name: "Artistic brushstroke interval splines",
        detail: "Sara L. Su et al.'s variable-width brushstroke model informed the independent SVG dab animation used for KanjiVG playback.",
        url: "https://people.csail.mit.edu/sarasu/pub/cgim02/cgim02.pdf",
      },
      {
        name: "DynaDraw",
        detail: "Paul Haeberli's dynamic-brush model informed the independent SVG ribbon-and-dab construction used for the playback effect.",
        url: "https://www.graficaobscura.com/dyna/",
      },
      {
        name: "Jitendex",
        detail: "Dictionary source used through the local compressed database generated by kentaromiura/jitendex-analysis. Jitendex is CC BY-SA 4.0 and includes JMdict, Tatoeba, Kanji alive audio, and JmdictFurigana materials under their source licenses.",
        url: "https://jitendex.org/pages/legal.html",
      },
      {
        name: "jitendex-analysis",
        detail: "Local pipeline used to build the compressed Jitendex databases referenced by this app.",
        url: "https://github.com/kentaromiura/jitendex-analysis",
      },
      {
        name: "Houhou SRS",
        detail: "Reference app and source for bundled KANJIDIC2, JMdict, JmdictFurigana, JLPT, word-frequency, and kanji-frequency resources. Local license file is Creative Commons Attribution ShareAlike.",
        url: "https://github.com/Doublevil/Houhou-SRS",
      },
      {
        name: "KKLC ordering helper",
        detail: "Kanji ordering and page-reference helper for Kodansha Kanji Learner's Course lookup. Source helper is GPL 3.0.",
        url: "https://github.com/retrazil/kanji_order",
      },
      {
        name: "Ulrike's Mnemonics",
        detail: "Optional mnemonic text from Joy o' Kanji, credited to Ulrike's Mnemonics.",
        url: "https://www.joyokanji.com/ulrikes-mnemonics",
      },
      {
        name: "Topokanji",
        detail: "Aozora, news, Twitter, and Wikipedia kanji-frequency corpora for text coverage estimates. CC BY 4.0.",
        url: "https://github.com/scriptin/topokanji/tree/master/data/kanji-frequency",
      },
      {
        name: "Open Spaced Repetition",
        detail: "FSRS-7 scheduling references and benchmark comparison.",
        url: "https://github.com/open-spaced-repetition/srs-benchmark",
      },
      {
        name: "fsrs-rs FSRS-7 PR",
        detail: "FSRS-7 dual-trace runtime formula and 34-parameter defaults.",
        url: "https://github.com/open-spaced-repetition/fsrs-rs/pull/426",
      },
      {
        name: "JLPT reference lists",
        detail: "Modern unofficial JLPT level references cross-checked against JLPTMatome's current N5-N1 kanji data.",
        url: "https://www.jlptmatome.com/",
      },
      {
        name: "OpenGameArt sounds",
        detail: "Bubble Pop / Plop.ogg by pokmon63, CC BY 3.0; Card Game sounds by HaelDB, CC0.",
        url: "https://opengameart.org/content/bubble-pop",
      },
    ]
    let creditRow = credit =>
      <CreditItem key={credit.name}>
        <CreditTitleLine>
          <CreditLink href={credit.url} target="_blank" rel="noreferrer">
            {str(credit.name)}
          </CreditLink>
        </CreditTitleLine>
        <DetailLine> {str(credit.detail)} </DetailLine>
      </CreditItem>

    <StatsPanel>
      <StudiedHeaderBar>
        <Heading> {str("Stats")} </Heading>
        <ModeTabs>
          <ModeButton active=true onClick={_ => ()}> {str("Stats")} </ModeButton>
          <ModeButton active=false onClick={_ => onShowStudied()}> {str("Studied")} </ModeButton>
        </ModeTabs>
      </StudiedHeaderBar>
      <StatsGrid>
        <StatCard>
          <SmallLabel> {str("2300 kanji progress")} </SmallLabel>
          <StatNumber> {str(percentString(learned, kanjiMasteryTarget))} </StatNumber>
          <StatMeter>
            <StatMeterFill
              style={ReactDOMStyle.make(~width=clampedPercentStyle(learned, kanjiMasteryTarget), ())}
            />
          </StatMeter>
          <DetailLine>
            {str(Int.toString(learned) ++ " / " ++ Int.toString(kanjiMasteryTarget) ++ " kanji")}
          </DetailLine>
        </StatCard>
        <StatCard>
          <SmallLabel> {str("Due now")} </SmallLabel>
          <StatNumber> {str(Int.toString(dashboard.dueCount))} </StatNumber>
          <DetailLine>
            {str(
              Int.toString(dashboard.dueCards) ++
              " cards ready in the review bucket",
            )}
          </DetailLine>
        </StatCard>
        <StatCard>
          <SmallLabel> {str("Kanji state")} </SmallLabel>
          <StatNumber> {str(Int.toString(learned))} </StatNumber>
          <DetailLine>
            {str(
              Int.toString(dashboard.seenKanji) ++
              " seen, " ++
              Int.toString(dashboard.learningKanji) ++
              " learning, " ++
              Int.toString(dashboard.masteredKanji) ++
              " mastered",
            )}
          </DetailLine>
        </StatCard>
        <StatCard>
          <SmallLabel> {str("Card coverage")} </SmallLabel>
          <StatNumber> {str(Int.toString(dashboard.learnedCards) ++ " / " ++ Int.toString(dashboard.totalCards))} </StatNumber>
          <DetailLine>
            {str("Individual prompts learned across kana, meaning, and kanji directions")}
          </DetailLine>
        </StatCard>
        <StatCard>
          <SmallLabel> {str("Text coverage estimate")} </SmallLabel>
          <ScheduleList>
            {chartStats.coverageEstimates
            ->Array.map(estimate => {
              <ScheduleRow key={estimate.label}>
                <span> {str(estimate.label)} </span>
                <ScheduleBar>
                  <ScheduleFill style={ReactDOMStyle.make(~width=estimate.fill, ())} />
                </ScheduleBar>
                <span> {str(estimate.percent)} </span>
              </ScheduleRow>
            })
            ->React.array}
          </ScheduleList>
          <DetailLine> {str("Weighted by corpus kanji frequency")} </DetailLine>
        </StatCard>
        <StatCard>
          <SmallLabel> {str("JLPT kanji")} </SmallLabel>
          <ScheduleList>
            {chartStats.jlptBuckets
            ->Array.map(bucket => {
              <ScheduleRow key={bucket.label}>
                <span> {str(bucket.label)} </span>
                <ScheduleBar>
                  <ScheduleFill style={ReactDOMStyle.make(~width=bucket.fill, ())} />
                </ScheduleBar>
                <span>
                  {str(
                    bucket.percent ++
                    " " ++ Int.toString(bucket.learned) ++ "/" ++ Int.toString(bucket.total),
                  )}
                </span>
              </ScheduleRow>
            })
            ->React.array}
          </ScheduleList>
        </StatCard>
        <StatCard>
          <SmallLabel> {str("Learn threshold")} </SmallLabel>
          <StatNumber> {str(Int.toString(settings.requiredCorrectStreak) ++ "x")} </StatNumber>
          <ModeTabs>
            {[1, 2, 3, 4]
            ->Array.map(value =>
              <ModeButton
                key={Int.toString(value)}
                active={settings.requiredCorrectStreak == value}
                onClick={_ => setRequiredStreak(value)}
              >
                {str(Int.toString(value))}
              </ModeButton>
            )
            ->React.array}
          </ModeTabs>
          <DetailLine> {str("Consecutive correct answers needed for one card")} </DetailLine>
        </StatCard>
        <StatCard>
          <SmallLabel> {str("Quick Review cards")} </SmallLabel>
          <StatNumber> {str(Int.toString(Array.length(settings.quickReviewKinds)) ++ " types")} </StatNumber>
          <ModeTabs>
            {quickReviewKindChoices
            ->Array.map(kind =>
              <ModeButton
                key={kind}
                active={hasQuickReviewKind(settings.quickReviewKinds, kind)}
                onClick={_ => toggleQuickReviewKind(kind)}
              >
                {str(srsKindLabel(kind))}
              </ModeButton>
            )
            ->React.array}
          </ModeTabs>
          <DetailLine> {str("Choose which prompt directions appear in Quick Review")} </DetailLine>
        </StatCard>
        <StatCard>
          <SmallLabel> {str("Overall reviews")} </SmallLabel>
          <StatNumber> {str(percentString(stats.correct, totalReviews))} </StatNumber>
          <DetailLine>
            {str(
              Int.toString(stats.correct) ++
              " correct, " ++ Int.toString(stats.wrong) ++ " wrong",
            )}
          </DetailLine>
        </StatCard>
        <StatCard>
          <SmallLabel> {str("Last 100 reviews")} </SmallLabel>
          <StatNumber> {str(percentString(stats.last100Correct, stats.last100Total))} </StatNumber>
          <DetailLine>
            {str(
              Int.toString(stats.last100Correct) ++
              " correct, " ++ Int.toString(last100Wrong) ++ " wrong",
            )}
          </DetailLine>
        </StatCard>
        <StatCard>
          <SmallLabel> {str("Backup")} </SmallLabel>
          <StatNumber> {str("JSON")} </StatNumber>
          <ModeTabs>
            <PrimaryButton onClick={_ => exportUserData()}> {str("Export")} </PrimaryButton>
            <PrimaryButton onClick={_ => importUserData(onDataImported)}> {str("Import")} </PrimaryButton>
          </ModeTabs>
          <DetailLine> {str("Move progress, stats, and options between devices")} </DetailLine>
        </StatCard>
      </StatsGrid>
      <SplitList>
        {[
          countRow("Due kanji -> kana", dashboard.kanjiToKanaDue),
          countRow("Due kanji -> meaning", dashboard.kanjiToMeaningDue),
          countRow("Due kana -> meaning", dashboard.kanaToMeaningDue),
          countRow("Due meaning -> kanji", dashboard.meaningToKanjiDue),
          countRow("Due meaning -> kana", dashboard.meaningToKanaDue),
          splitRow("Kanji -> kana", stats.kanjiToKanaCorrect, stats.kanjiToKanaWrong),
          splitRow("Kanji -> meaning", stats.kanjiToMeaningCorrect, stats.kanjiToMeaningWrong),
          splitRow("Kana -> meaning", stats.kanaToMeaningCorrect, stats.kanaToMeaningWrong),
          splitRow("Meaning -> kanji", stats.meaningToKanjiCorrect, stats.meaningToKanjiWrong),
          splitRow("Meaning -> kana", stats.meaningToKanaCorrect, stats.meaningToKanaWrong),
        ]->React.array}
      </SplitList>
      <CreditsPanel>
        <SmallLabel> {str("Credits and licenses")} </SmallLabel>
        <CreditList> {credits->Array.map(creditRow)->React.array} </CreditList>
        <DetailLine>
          {str("This app is not affiliated with the projects above; they are credited for source data, references, algorithms, and audio assets used or planned in the learning experience.")}
        </DetailLine>
      </CreditsPanel>
    </StatsPanel>
  }
